# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  setup_foo:
    docker:
      - image: cimg/go:1.17
    steps:
      - run:
          name: mkdir my_cache
          command: mkdir ~/my_cache
      - run:
          name: add first file
          command: echo foo1 > ~/my_cache/file1.txt
      - save_cache:
          key: cache_test_v1
          paths:
            - ~/my_cache
      - run:
          name: add second file
          command: echo foo2 > ~/my_cache/file2.txt
      - restore_cache:
          keys:
            - cache_test_v1
      - run:
          name: ls
          command: ls -la ~/my_cache
      - run:
          name: setting up work env
          command: echo foo > foo.txt
      - restore_cache:
          keys:
            - go-global-v2    
      - run:
          name: go protoc
          command: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - save_cache:
          key: go-global-v2
          paths:
            - ~/go/bin
            - ~/go/pkg/mod
            - ~/.cache
      - persist_to_workspace:
          root: "~/"
          # Must be relative path from root
          paths:
            - my_cache
            - go
            - .cache
  build_hello:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.17
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    resource_class: small
    steps:
      - checkout
      - run:
          name: ls
          command: ls -la ~/my_cache || true
      - run:
          name: checking env.
          command: cat foo.txt || true
      - run:
          name: check environment
          command: |
            pwd
            ls 
            ls ~
            ls ~/repo
            ls ~/go/pkg/mod || true
            true
      - restore_cache:
          keys:
            - go-mod-v6-{{ checksum "hello/go.sum" }}
            - go-global-v2
      - run:
          name: check cache path after
          command: ls ~/go/pkg/mod || true
      - run:
          name: Install Dependencies
          command: make -C hello download
      - save_cache:
          key: go-mod-v6-{{ checksum "hello/go.sum" }}
          paths:
            - ~/go/pkg/mod
            - ~/.cache 
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            cd hello
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
      - run:
          name: check environment
          command: |
            pwd
            ls 
            ls ~
            ls ~/repo
            ls ~/go/pkg/mod || true
            true  

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build_hello:
          requires:
            - setup_foo
      - setup_foo
